### ISSUE TITLE
У меня оишбка появилась

### ISSUE THREAD

**Issue by Diseerr** [Fequme/Disnake-events-bot#2]
Traceback (most recent call last):
  File "c:\Users\corny\OneDrive\Desktop\Events\main.py", line 12, in <module>
    client = commands.Bot(command_prefix='s!123dlks', intents=disnake.Intents.all(
  File "C:\Users\corny\AppData\Roaming\Python\Python310\site-packages\disnake\ext\commands\bot_base.py", line 130, in __init__
    super().__init__(**options)
  File "C:\Users\corny\AppData\Roaming\Python\Python310\site-packages\disnake\ext\commands\interaction_bot_base.py", line 154, in __init__
    raise ValueError("test_guilds must be a sequence of int.")
ValueError: test_guilds must be a sequence of int.

**Comment by Fequme** [comment]
переменная test_guilds должна быть числом

**Comment by Diseerr** [comment]
> переменная test_guilds должна быть числом

Где?
